stat_svc
ebogacheva/java-explore-with-me pull request #3
Opened 2023-07-18 21:00 UTC by ebogacheva

2023-07-20 13:25 UTC, Fleaman777 requested changes

2023-07-20 13:25 UTC, Fleaman777 commented on docker-compose.yml
> +      - EWM_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm
сейчас получается, что значения переменных окружения, EWM_DATASOURCE_URL, не используются, т.к. в application.properties они не проставлены

2023-07-20 13:25 UTC, Fleaman777 commented on stats-service/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +        }
эта логика проверки должна быть на уровне сервиса

2023-07-20 19:20 UTC, ebogacheva commented on stats-service/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +        }
Перенесла проверку в сервис.

2023-07-21 14:54 UTC, Fleaman777 approved these changes

2023-07-24 13:59 UTC, merged