Main svc
ebogacheva/java-explore-with-me pull request #4
Opened 2023-08-08 08:01 UTC by ebogacheva

2023-08-08 18:54 UTC, Fleaman777 requested changes

2023-08-08 18:54 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/category/controller/CategoryAdminController.java
> +    CategoryDto create(@Valid @RequestBody NewCategoryDto category) {
лучше проставить модификтора доступа public,
на 1й взгляд может показаться, что и так работает,
но что там внтури у спринга до конца не известно, и возможно какой-то функционал не будет работать

аналагично в др местах

2023-08-08 18:54 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +    public List<CategoryDto> get(Integer from, Integer size) {
На методах, предназначенных для чтения данных рекомендую использовать транзакцию только для чтения:
@Transactional(readOnly = true)

2023-08-08 18:54 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    @Column(name = "id")
если названия параметра name совпадает с названием поля, то можно не указывать аннотацию, 
что в целом хорошо, т.к. будет меньше кода, меньше отвлекающих факторов, 
к тому же, если все таки где-то название колонки не будет совпадать с названием поля, то мы это точно не пропустим, т.к. у нас аннотация Column будет висеть только в тех местах, где это действительно необходимо

2023-08-08 18:54 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        List<EventShortDto> dtos = getEventShortDtos(events); // TODO: обязательно попробовать что работает без передачи листа ДТО
попробовала?)

2023-08-08 18:54 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/repository/CustomEventRepositoryImpl.java
> +        if (Objects.isNull(params.getRangeStart())) {
почему бы по обычному не проверить  на null. 
params.getRangeStart() == null  ?

2023-08-08 18:54 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +    private static void checkUserIsInitiator(Long userId, Event event) {
а нужно ли этот и следующий метод делать с модификатором static ?

2023-08-08 18:54 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/utils/ExploreConstantsAndStaticMethods.java
> +public class ExploreConstantsAndStaticMethods {
здесь можно повесить ломбок аннотацию @UtilityClass 
она пометит все методы класса как статические, а так же создаст приватный конструктор 
в итоге часть бойлер плейт кода нам не нужно будет писать
относится ко всем аналогичным местам

2023-08-08 18:54 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/utils/ExploreDateTimeFormatter.java
> +public class ExploreDateTimeFormatter {
аналагично предыдущему комментарию

2023-08-09 10:31 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/category/controller/CategoryAdminController.java
> +    CategoryDto create(@Valid @RequestBody NewCategoryDto category) {
Да, исправила.

2023-08-09 10:35 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +    public List<CategoryDto> get(Integer from, Integer size) {
Сделала.

2023-08-09 10:43 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/event/repository/CustomEventRepositoryImpl.java
> +        if (Objects.isNull(params.getRangeStart())) {
Да, так лучше)

2023-08-09 10:44 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +    private static void checkUserIsInitiator(Long userId, Event event) {
Нет, но статик-методы в среде курсивом выделяются и мне так легче их "читать".
По сути - нет, не нужно. Исправила.

2023-08-09 10:46 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/utils/ExploreConstantsAndStaticMethods.java
> +public class ExploreConstantsAndStaticMethods {
Сделала

2023-08-09 10:46 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/utils/ExploreDateTimeFormatter.java
> +public class ExploreDateTimeFormatter {
Сделала

2023-08-09 11:00 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        List<EventShortDto> dtos = getEventShortDtos(events); // TODO: обязательно попробовать что работает без передачи листа ДТО
Даааа) Теперь попробовала, убрала лишний метод. Все "само" работает.

2023-08-09 11:05 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    @Column(name = "id")
Сделала. Вообще мне было так легче фиксировать в голове, что и как я делаю, как называю колонки и т.д. 
Но, конечно, лишнее нужно убирать.

2023-08-10 09:24 UTC, Fleaman777 approved these changes

2023-08-11 15:43 UTC, merged