Feature subscriptions
ebogacheva/java-explore-with-me pull request #5
Opened 2023-08-13 21:24 UTC by ebogacheva

2023-08-14 12:47 UTC, Fleaman777 requested changes

2023-08-14 12:47 UTC, Fleaman777 commented on README.md
>  Template repository for ExploreWithMe project.
сюда можно было бы немного добавить описание проекта

2023-08-15 20:57 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/subscription/model/Subscription.java
> +    private Long user1Id;
Ох, сколько раз я их всех переименовывала...))
Поменяла. В контроллере и сервисе оставила user, а other превратила тоже в owner.

2023-08-15 21:09 UTC, ebogacheva commented on main-service/src/main/java/ru/practicum/subscription/service/SubscriptionServiceImpl.java
> +    public void subscribe(Long userId, Long otherId, SubscriptionType type) {
Сделала.

2023-08-15 21:52 UTC, ebogacheva commented on README.md
>  Template repository for ExploreWithMe project.
Ага. Добавила. Ссылку на PR оставила в начала файла.

2023-08-16 18:37 UTC, Fleaman777 approved these changes

2023-08-16 18:37 UTC, Fleaman777 commented on README.md
> +![img.png](img.png)
красиво

2023-08-16 20:39 UTC, merged